var repo = require("../../services/repository.js");
Page({
  data: { trip: null, selectedPhotos: 0, selectedDiary: 0, generated: false, shareToken: "" },
  onLoad: function (options) { var self = this; this.tripId = options.tripId; repo.getTrip(options.tripId).then(function (trip) { self.setData({ trip: trip, selectedPhotos: (trip.days || []).reduce(function (n, d) { return n + (d.photos || []).filter(function (p) { return p.shareSelected !== false; }).length; }, 0), selectedDiary: (trip.days || []).filter(function (d) { return d.diary && d.diary.updatedAt; }).length }); }); },
  togglePhoto: function (e) { var day = this.data.trip.days[Number(e.currentTarget.dataset.day)]; var photo = day.photos[Number(e.currentTarget.dataset.index)]; photo.shareSelected = photo.shareSelected === false; this.setData({ trip: this.data.trip, selectedPhotos: this.data.selectedPhotos + (photo.shareSelected ? 1 : -1) }); },
  toggleDiary: function (e) { var day = this.data.trip.days[Number(e.currentTarget.dataset.day)]; day.shareDiary = day.shareDiary === false; this.setData({ trip: this.data.trip, selectedDiary: this.data.selectedDiary + (day.shareDiary ? 1 : -1) }); },
  generate: function () { var self = this; repo.saveTrip(this.data.trip).then(function () { return repo.createShare(self.data.trip); }).then(function (share) { self.setData({ generated: true, shareToken: share.token }); wx.showModal({ title: "精选分享已生成", content: "有效7天 · 已选照片 " + self.data.selectedPhotos + " 张 · 日记 " + self.data.selectedDiary + " 天。现在可以转发。", showCancel: false }); }).catch(function () { wx.showToast({ title: "连接云端后才能生成分享", icon: "none" }); }); },
  revoke: function () { var self = this; repo.revokeShare(this.data.shareToken).then(function () { self.setData({ generated: false, shareToken: "" }); wx.showToast({ title: "分享已撤销", icon: "success" }); }); },
  onShareAppMessage: function () { if (!this.data.shareToken) return { title: "请先生成精选分享", path: "/pages/share/select?tripId=" + this.tripId }; return { title: this.data.trip ? this.data.trip.title : "我们的旅行绘本", path: "/pages/share/view?token=" + this.data.shareToken }; }
});
